alter table "public"."trials" add column "progressive" bigint generated by default as identity not null;

create policy "Enable insert for authenticated users only"
on "public"."trial_item_with_criteria"
as permissive
for insert
to authenticated
with check (true);


create policy "owner can delete"
on "public"."trial_item_with_criteria"
as permissive
for delete
to authenticated
using ((EXISTS ( SELECT 1
   FROM trials,
    trial_item
  WHERE ((trial_item.id = trial_item_with_criteria.trial_item_id) AND (trials.id = trial_item.trial_id) AND (trials.owner_id = auth.uid())))));


create policy "owner can select"
on "public"."trial_item_with_criteria"
as permissive
for select
to authenticated
using ((EXISTS ( SELECT 1
   FROM trials,
    trial_item
  WHERE ((trial_item.id = trial_item_with_criteria.trial_item_id) AND (trials.id = trial_item.trial_id) AND (trials.owner_id = auth.uid())))));


create policy "owner can update"
on "public"."trial_item_with_criteria"
as permissive
for update
to authenticated
using ((EXISTS ( SELECT 1
   FROM trials,
    trial_item
  WHERE ((trial_item.id = trial_item_with_criteria.trial_item_id) AND (trials.id = trial_item.trial_id) AND (trials.owner_id = auth.uid())))));



