create table "public"."criteria" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "criteria_name" text not null,
    "criteria_description" text
);


alter table "public"."criteria" enable row level security;

create table "public"."measures" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "measure_name" text not null
);


alter table "public"."measures" enable row level security;

create table "public"."trial_item" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "trial_id" uuid not null,
    "item_text" timestamp with time zone
);


alter table "public"."trial_item" enable row level security;

create table "public"."trial_item_with_criteria" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "trial_item_id" bigint,
    "criteria_id" bigint,
    "min_value" integer not null,
    "max_value" integer not null
);


alter table "public"."trial_item_with_criteria" enable row level security;

create table "public"."trial_items_answers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "partecipant_id" bigint not null,
    "trial_item_id" bigint not null,
    "criteria_id" bigint,
    "turn" integer not null,
    "score" integer not null
);


alter table "public"."trial_items_answers" enable row level security;

create table "public"."trial_measures" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "trial_id" uuid not null,
    "measure_id" bigint not null,
    "score" double precision not null
);


alter table "public"."trial_measures" enable row level security;

create table "public"."trial_partecipant" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "trial_id" uuid not null,
    "partecipant_id" character varying,
    "isPresent" boolean
);


alter table "public"."trial_partecipant" enable row level security;

create table "public"."trials" (
    "id" uuid not null,
    "created_at" timestamp with time zone default now(),
    "owner_id" uuid not null,
    "exported" boolean not null default false,
    "exported_at" timestamp with time zone,
    "status" smallint not null default '0'::smallint
);


alter table "public"."trials" enable row level security;

CREATE UNIQUE INDEX measures_pkey ON public.measures USING btree (id);

CREATE UNIQUE INDEX trail_partecipant_pkey ON public.trial_partecipant USING btree (id);

CREATE UNIQUE INDEX trial_item_pkey ON public.trial_item USING btree (id);

CREATE UNIQUE INDEX trial_item_with_criteria_pkey ON public.trial_item_with_criteria USING btree (id);

CREATE UNIQUE INDEX trial_items_answers_pkey ON public.trial_items_answers USING btree (id);

CREATE UNIQUE INDEX trial_items_criteria_pkey ON public.criteria USING btree (id);

CREATE UNIQUE INDEX trial_measures_pkey ON public.trial_measures USING btree (id);

CREATE UNIQUE INDEX trials_pkey ON public.trials USING btree (id);

alter table "public"."criteria" add constraint "trial_items_criteria_pkey" PRIMARY KEY using index "trial_items_criteria_pkey";

alter table "public"."measures" add constraint "measures_pkey" PRIMARY KEY using index "measures_pkey";

alter table "public"."trial_item" add constraint "trial_item_pkey" PRIMARY KEY using index "trial_item_pkey";

alter table "public"."trial_item_with_criteria" add constraint "trial_item_with_criteria_pkey" PRIMARY KEY using index "trial_item_with_criteria_pkey";

alter table "public"."trial_items_answers" add constraint "trial_items_answers_pkey" PRIMARY KEY using index "trial_items_answers_pkey";

alter table "public"."trial_measures" add constraint "trial_measures_pkey" PRIMARY KEY using index "trial_measures_pkey";

alter table "public"."trial_partecipant" add constraint "trail_partecipant_pkey" PRIMARY KEY using index "trail_partecipant_pkey";

alter table "public"."trials" add constraint "trials_pkey" PRIMARY KEY using index "trials_pkey";

alter table "public"."trial_item" add constraint "trial_item_trial_id_fkey" FOREIGN KEY (trial_id) REFERENCES trials(id) ON DELETE CASCADE not valid;

alter table "public"."trial_item" validate constraint "trial_item_trial_id_fkey";

alter table "public"."trial_item_with_criteria" add constraint "trial_item_with_criteria_criteria_id_fkey" FOREIGN KEY (criteria_id) REFERENCES criteria(id) ON DELETE CASCADE not valid;

alter table "public"."trial_item_with_criteria" validate constraint "trial_item_with_criteria_criteria_id_fkey";

alter table "public"."trial_item_with_criteria" add constraint "trial_item_with_criteria_trial_item_id_fkey" FOREIGN KEY (trial_item_id) REFERENCES trial_item(id) ON DELETE CASCADE not valid;

alter table "public"."trial_item_with_criteria" validate constraint "trial_item_with_criteria_trial_item_id_fkey";

alter table "public"."trial_items_answers" add constraint "trial_items_answers_criteria_id_fkey" FOREIGN KEY (criteria_id) REFERENCES criteria(id) ON DELETE CASCADE not valid;

alter table "public"."trial_items_answers" validate constraint "trial_items_answers_criteria_id_fkey";

alter table "public"."trial_items_answers" add constraint "trial_items_answers_partecipant_id_fkey" FOREIGN KEY (partecipant_id) REFERENCES trial_partecipant(id) ON DELETE CASCADE not valid;

alter table "public"."trial_items_answers" validate constraint "trial_items_answers_partecipant_id_fkey";

alter table "public"."trial_items_answers" add constraint "trial_items_answers_trial_item_id_fkey" FOREIGN KEY (trial_item_id) REFERENCES trial_item(id) ON DELETE CASCADE not valid;

alter table "public"."trial_items_answers" validate constraint "trial_items_answers_trial_item_id_fkey";

alter table "public"."trial_measures" add constraint "trial_measures_measure_id_fkey" FOREIGN KEY (measure_id) REFERENCES measures(id) ON DELETE CASCADE not valid;

alter table "public"."trial_measures" validate constraint "trial_measures_measure_id_fkey";

alter table "public"."trial_measures" add constraint "trial_measures_trial_id_fkey" FOREIGN KEY (trial_id) REFERENCES trials(id) ON DELETE CASCADE not valid;

alter table "public"."trial_measures" validate constraint "trial_measures_trial_id_fkey";

alter table "public"."trial_partecipant" add constraint "trial_partecipant_trial_id_fkey" FOREIGN KEY (trial_id) REFERENCES trials(id) not valid;

alter table "public"."trial_partecipant" validate constraint "trial_partecipant_trial_id_fkey";

alter table "public"."trials" add constraint "trials_owner_id_fkey" FOREIGN KEY (owner_id) REFERENCES auth.users(id) not valid;

alter table "public"."trials" validate constraint "trials_owner_id_fkey";


